require 'plugins'
require 'settings.core_settings'
require 'keybindings.tabs'
require 'keybindings.open_config'
require 'plugins.neotree'
require 'keybindings.neotree'
require 'keybindings.panels'
-- require 'plugins.bufferline'
-- require 'keybindings.bufferline'
require 'keybindings.editing'
require 'plugins.flash'
require 'keybindings.flash'
require 'active_theme'
require 'parsers.sv_parser'
-- require 'plugins.lualine'
require 'plugins.luasnip'
require 'load_snippets'
require 'plugins.toggleterm'
require 'plugins.autopairs'
require 'plugins.smear-cursor'
require 'diagnostic.open_on_hover'
require 'keybindings.telescope'
require 'lsp.veridian'
require 'lsp.jedi'
require 'plugins.treesitter'
require 'plugins.coc'
require 'lsp.rust-analyzer'
require 'lsp.tinymist'
require 'plugins.cyrillic'
require 'keybindings.core'
require 'plugins.dap'
