require 'plugins.plugins'
require 'plugins.neotree'
require 'plugins.flash'
require 'plugins.lualine'
require 'plugins.toggleterm'
require 'plugins.autopairs'
require 'plugins.treesitter'
require 'plugins.cyrillic'
require 'plugins.cmp'
require 'plugins.dap'

require 'settings.theme'
require 'settings.core_settings'

require 'lsp.pyright'
require 'lsp.veridian'
require 'lsp.tinymist'
require 'lsp.clangd'
require 'lsp.gopls'
require 'lsp.veryl'

require 'parsers.sv_parser'

require 'diagnostic.open_on_hover'

require 'keybindings.tabs'
require 'keybindings.open_config'
require 'keybindings.neotree'
require 'keybindings.panels'
require 'keybindings.editing'
require 'keybindings.telescope'
require 'keybindings.flash'
require 'keybindings.core'
require 'keybindings.theme'
require 'keybindings.lsp'
require 'keybindings.dap'

